#!/bin/sh
# Format staged Kotlin files with the project's Spotless/ktlint configuration.
CHANGED_FILES="$(git --no-pager diff --name-only --cached --diff-filter=ACMRTUXB --relative | grep '\.kts\?$')"
if [ -z "$CHANGED_FILES" ]; then
  echo "No Kotlin staged files."
  exit 0
fi

echo "Running spotlessApply over these files:"
echo "$CHANGED_FILES"

if ! ./gradlew --quiet spotlessApply; then
  exit 1
fi

echo "Completed spotlessApply run."
echo "$CHANGED_FILES" | while read -r file; do
  if [ -f "$file" ]; then
    git add "$file"
  fi
done
