name: Build

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4096M -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.caching=true"

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Gradle setup
        uses: ./.github/actions/gradle-setup

      - name: Run unit tests
        run: ./gradlew jvmTest testAndroidHostTest

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: "**/build/reports/tests/"

  code-style:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Gradle setup
        uses: ./.github/actions/gradle-setup

      - name: Check code style
        run: ./gradlew spotlessCheck

  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Gradle setup
        uses: ./.github/actions/gradle-setup

      - name: Build Android debug APK
        run: ./gradlew :sample:androidApp:assembleDebug

      - name: Upload Android debug APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: sample/androidApp/build/outputs/apk/debug/*.apk

  build-ios:
    name: Build iOS simulator app
    runs-on: macos-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Gradle setup
        uses: ./.github/actions/gradle-setup

      - name: Check public API
        run: ./gradlew :kscan:checkLegacyAbi

      - name: Run iOS unit tests
        run: ./gradlew :kscan:iosSimulatorArm64Test

      - name: Build iOS simulator app
        run: |
          xcodebuild build \
          -project sample/iosApp/iosApp.xcodeproj \
          -configuration Debug \
          -scheme iosApp \
          -sdk iphonesimulator \
          -arch arm64 \
          -derivedDataPath ./build

      - name: Upload App Folder
        uses: actions/upload-artifact@v4
        with:
          name: iphonesimulator-app
          path: build/Build/Products/Debug-iphonesimulator/*

  build-desktop-macos:
    name: Build Desktop macOS
    runs-on: macos-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Gradle setup
        uses: ./.github/actions/gradle-setup

      - name: Build macOS DMG
        run: ./gradlew :sample:desktopApp:packageDmg

      - name: Upload macOS DMG
        uses: actions/upload-artifact@v4
        with:
          name: desktop-macos-dmg
          path: sample/desktopApp/build/compose/binaries/main/dmg/*.dmg

  build-desktop-windows:
    name: Build Desktop Windows
    runs-on: windows-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Gradle setup
        uses: ./.github/actions/gradle-setup

      - name: Build Windows MSI
        run: ./gradlew :sample:desktopApp:packageMsi

      - name: Upload Windows MSI
        uses: actions/upload-artifact@v4
        with:
          name: desktop-windows-msi
          path: sample/desktopApp/build/compose/binaries/main/msi/*.msi

  build-desktop-linux:
    name: Build Desktop Linux
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Gradle setup
        uses: ./.github/actions/gradle-setup

      - name: Build Linux DEB
        run: ./gradlew :sample:desktopApp:packageDeb

      - name: Upload Linux DEB
        uses: actions/upload-artifact@v4
        with:
          name: desktop-linux-deb
          path: sample/desktopApp/build/compose/binaries/main/deb/*.deb

  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Gradle setup
        uses: ./.github/actions/gradle-setup

      - name: Build web distributions
        run: ./gradlew :sample:webApp:wasmJsBrowserDistribution :sample:webApp:jsBrowserDistribution

      - name: Upload Wasm app
        uses: actions/upload-artifact@v4
        with:
          name: wasm-app
          path: sample/webApp/build/dist/wasmJs/productionExecutable/

      - name: Upload JS app
        uses: actions/upload-artifact@v4
        with:
          name: js-app
          path: sample/webApp/build/dist/js/productionExecutable/
