name: Publish Wiki

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'sample/**'
      - 'docs/**'
  workflow_dispatch:

concurrency:
  group: publish-wiki
  cancel-in-progress: true

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4096M -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.caching=true"

jobs:
  publish-wiki:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Gradle setup
        uses: ./.github/actions/gradle-setup

      - name: Generate API documentation
        run: ./gradlew dokkaGenerate

      - name: Upload Wiki
        uses: JamesIves/github-pages-deploy-action@fa24774553152dd7873cd16ebd8d959b010c5445 # v4.9.0
        with:
          folder: ./build/dokka/html
          branch: gh-pages
          force: true
